git:
  disableForcePushing: true
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --diff-highlight --paging=never
gui:
  authorColors:
    "*": yellow
  useHunkModeInStagingView: false
