git:
  disableForcePushing: true
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: /usr/share/git/diff-highlight/diff-highlight
gui:
  authorColors:
    "*": yellow
  useHunkModeInStagingView: false
